GET http://localhost:3000/dogs

###

GET http://localhost:3000/dogs/2

###

POST http://localhost:3000/dogs
Content-Type: application/json

{
    "id": 4,
    "name": "Belle",
    "age": 12,
    "likes": "wood sticks"
}

###

PUT http://localhost:3000/dogs/3

###

DELETE http://localhost:3000/dogs
Content-Type: application/json

###
